"""Samocode worker package - core orchestrator components."""

from .adapters import supported_providers
from .approval import (
    ApprovalCheck,
    ApprovalOutcome,
    ApprovalPlan,
    ApprovalRejection,
    ApprovalResult,
    approve,
    approve_session,
    check_approval,
    exit_code_for,
)
from .config import (
    ProjectConfig,
    RuntimeConfig,
    SamocodeConfig,
    parse_samocode_file,
    resolve_session_path,
)
from .final_polish import (
    FinalPolishCheck,
    validate_final_polish,
    validate_final_polish_evidence,
)
from .global_config import (
    ConfigBootstrapResult,
    ConfigBootstrapStatus,
    GlobalConfig,
    GlobalConfigError,
    ensure_global_config,
    global_config_path,
)
from .installer import (
    InstallMode,
    InstallOutcome,
    InstallResult,
    UninstallOutcome,
    UninstallResult,
    install,
    uninstall,
)
from .lifecycle import (
    EpochPhaseRunCount,
    LifecycleCheck,
    LifecycleIssue,
    LifecycleIssueCode,
    RecoveryAnchor,
    count_epoch_source_phase_runs_including_current,
    count_escalations_since_phase_entry,
    latest_applied_recovery_anchor,
    recovery_commit_marker,
    scoped_history,
    validate_final_polish_lifecycle,
    validate_phase_provenance,
)
from .logging import add_session_handler, setup_logging
from .notifications import notify_blocked, notify_complete, notify_error, notify_waiting
from .phases import (
    PHASE_CONFIGS,
    ApprovalGate,
    EscalationPolicy,
    Phase,
    PhaseConfig,
    PhaseRegistryError,
    get_agent_for_phase,
    get_phase_config,
    is_iteration_limit_exceeded,
    validate_phase_registry,
    validate_signal_for_phase,
    validate_transition,
)
from .plan_resolver import PlanResolutionError
from .process_lease import (
    ProcessLease,
    ProcessLeaseState,
    acquire_process_lease,
)
from .recovery import (
    RecoveryInspection,
    RecoveryOutcome,
    RecoveryRejection,
    RecoveryResult,
    RecoveryStateFingerprint,
    inspect_final_polish_recovery,
    recover_final_polish,
    recovery_exit_code,
)
from .routing import (
    ExecutionResolutionError,
    ProfileSource,
    ResolvedProfile,
    resolve_workflow_profile,
    validate_workflow_overrides,
)
from .runner import (
    EscalationContext,
    ExecutionResult,
    ExecutionStatus,
    extract_phase,
    extract_total_iterations,
    increment_total_iterations,
    latest_test_report,
    resolve_working_dir,
    run_ai_with_retry,
    run_claude_with_retry,
    validate_session_structure,
)
from .signal_history import (
    ESCALATION_STATUS,
    HistoryRecord,
    SignalHistoryEntry,
    count_source_phase_iterations,
    count_source_phase_iterations_including_current,
    get_phase_iteration_count,
    read_history,
    read_signal_history,
    record_escalation,
    record_processed_outcome,
    record_signal,
)
from .signals import (
    BLOCKED_NEEDS,
    OVERVIEW_FILENAME,
    SIGNAL_FILENAME,
    WORKER_NEEDS,
    Signal,
    SignalStatus,
    clear_signal_file,
    read_signal_file,
)
from .startup import (
    LEGACY_DEFAULT_PROVIDER,
    StartupComposition,
    compose_startup,
    load_global_config,
    select_provider,
)
from .timestamps import (
    FILE_TIMESTAMP_PATTERN,
    FOLDER_TIMESTAMP_PATTERN,
    file_timestamp,
    folder_timestamp,
    full_timestamp,
    iteration_timestamp,
    jsonl_timestamp,
    log_timestamp,
)
from .workflow_event import (
    RejectionReason,
    WorkflowEvent,
    WorkflowEventResult,
    validate_workflow_event,
)
from .worktree_guard import (
    WorktreeSnapshot,
    describe_worktree_mutation,
    snapshot_worktree,
)
from .workflow_state import (
    OutcomeKind,
    OverviewParseError,
    OverviewParseResult,
    OverviewState,
    OverviewTransition,
    OverviewWriteError,
    OverviewWriteFailure,
    OverviewWriteResult,
    ProcessedOutcome,
    apply_overview_transition,
    apply_overview_transition_locked,
    apply_workflow_event,
    atomic_write_text,
    parse_overview_state,
    read_overview_state,
    render_overview,
)

__all__ = [
    # Approval
    "ApprovalCheck",
    "ApprovalOutcome",
    "ApprovalPlan",
    "ApprovalRejection",
    "ApprovalResult",
    "approve",
    "approve_session",
    "check_approval",
    "exit_code_for",
    # Config
    "ProjectConfig",
    "RuntimeConfig",
    "SamocodeConfig",
    "parse_samocode_file",
    "resolve_session_path",
    # Global config
    "ConfigBootstrapResult",
    "ConfigBootstrapStatus",
    "GlobalConfig",
    "GlobalConfigError",
    "ensure_global_config",
    "global_config_path",
    # Installer
    "InstallMode",
    "InstallOutcome",
    "InstallResult",
    "UninstallOutcome",
    "UninstallResult",
    "install",
    "uninstall",
    "FinalPolishCheck",
    "validate_final_polish",
    "validate_final_polish_evidence",
    # Lifecycle
    "EpochPhaseRunCount",
    "LifecycleCheck",
    "LifecycleIssue",
    "LifecycleIssueCode",
    "RecoveryAnchor",
    "count_epoch_source_phase_runs_including_current",
    "count_escalations_since_phase_entry",
    "latest_applied_recovery_anchor",
    "scoped_history",
    "recovery_commit_marker",
    "validate_final_polish_lifecycle",
    "validate_phase_provenance",
    # Process lease
    "ProcessLease",
    "ProcessLeaseState",
    "acquire_process_lease",
    # Recovery
    "RecoveryInspection",
    "RecoveryOutcome",
    "RecoveryRejection",
    "RecoveryResult",
    "RecoveryStateFingerprint",
    "inspect_final_polish_recovery",
    "recover_final_polish",
    "recovery_exit_code",
    # Logging
    "add_session_handler",
    "setup_logging",
    # Notifications
    "notify_blocked",
    "notify_complete",
    "notify_error",
    "notify_waiting",
    # Phases
    "ApprovalGate",
    "EscalationPolicy",
    "Phase",
    "PhaseConfig",
    "PhaseRegistryError",
    "PHASE_CONFIGS",
    "get_agent_for_phase",
    "get_phase_config",
    "is_iteration_limit_exceeded",
    "validate_phase_registry",
    "validate_signal_for_phase",
    "validate_transition",
    # Routing
    "ExecutionResolutionError",
    "PlanResolutionError",
    "ProfileSource",
    "ResolvedProfile",
    "resolve_workflow_profile",
    "validate_workflow_overrides",
    # Runner
    "EscalationContext",
    "ExecutionResult",
    "ExecutionStatus",
    "extract_phase",
    "extract_total_iterations",
    "increment_total_iterations",
    "latest_test_report",
    "run_ai_with_retry",
    "run_claude_with_retry",
    "resolve_working_dir",
    "validate_session_structure",
    # Signal history
    "ESCALATION_STATUS",
    "HistoryRecord",
    "SignalHistoryEntry",
    "count_source_phase_iterations",
    "count_source_phase_iterations_including_current",
    "get_phase_iteration_count",
    "read_history",
    "read_signal_history",
    "record_escalation",
    "record_processed_outcome",
    "record_signal",
    # Signals
    "BLOCKED_NEEDS",
    "OVERVIEW_FILENAME",
    "SIGNAL_FILENAME",
    "WORKER_NEEDS",
    "Signal",
    "SignalStatus",
    "clear_signal_file",
    "read_signal_file",
    # Workflow events
    "RejectionReason",
    "WorkflowEvent",
    "WorkflowEventResult",
    "validate_workflow_event",
    # Worktree guard
    "WorktreeSnapshot",
    "describe_worktree_mutation",
    "snapshot_worktree",
    # Workflow state
    "OutcomeKind",
    "OverviewParseError",
    "OverviewParseResult",
    "OverviewState",
    "OverviewTransition",
    "OverviewWriteError",
    "OverviewWriteFailure",
    "OverviewWriteResult",
    "ProcessedOutcome",
    "apply_overview_transition",
    "apply_overview_transition_locked",
    "atomic_write_text",
    "parse_overview_state",
    "apply_workflow_event",
    "read_overview_state",
    "render_overview",
    # Startup
    "LEGACY_DEFAULT_PROVIDER",
    "StartupComposition",
    "compose_startup",
    "load_global_config",
    "select_provider",
    "supported_providers",
    # Timestamps
    "FILE_TIMESTAMP_PATTERN",
    "FOLDER_TIMESTAMP_PATTERN",
    "file_timestamp",
    "folder_timestamp",
    "full_timestamp",
    "iteration_timestamp",
    "jsonl_timestamp",
    "log_timestamp",
]
